# Generated by Django 6.0 on 2025-12-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Sarees, Gowns, Kurtis', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_desktop', models.ImageField(upload_to='slides/desktop')),
                ('image_mobile', models.ImageField(blank=True, upload_to='slides/mobile')),
                ('link_url', models.URLField(blank=True, help_text='Slide click redirect URL')),
                ('order', models.IntegerField(default=0, help_text='Display order (0, 1, 2...)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('purchase_product', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Testimonial',
                'verbose_name_plural': 'Customer Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, help_text='MRP', max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Selling price', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/')),
                ('image_hover', models.ImageField(blank=True, help_text='Hover image (optional)', null=True, upload_to='products/hover/')),
                ('fabric', models.CharField(blank=True, help_text='Ex: Silk, Cotton', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Ex: Red, Blue', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='Out of 5', max_digits=2)),
                ('review_count', models.IntegerField(default=0, help_text='Number of reviews')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Show in Bestsellers')),
                ('is_ready_to_wear', models.BooleanField(default=False, help_text='Ready to Wear collection')),
                ('is_wedding', models.BooleanField(default=False, help_text='Wedding collection')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on homepage')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available quantity')),
                ('is_active', models.BooleanField(default=True, help_text='Visible on website')),
                ('display_order', models.IntegerField(default=0, help_text='Display priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='home.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', '🟡 Pending Payment'), ('confirmed', '🟢 Payment Confirmed'), ('processing', '📦 Processing'), ('shipped', '🚚 Shipped'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('refunded', '💰 Refunded')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, help_text='Courier tracking ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.product')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
