# Generated by Django 6.0 on 2025-12-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_desktop', models.ImageField(upload_to='slides/desktop/')),
                ('image_mobile', models.ImageField(blank=True, upload_to='slides/mobile/')),
                ('link_url', models.URLField(blank=True, help_text='Slide click చేసినప్పుడు redirect URL')),
                ('order', models.IntegerField(default=0, help_text='Display order (0, 1, 2...)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
    ]
