# Generated by Django 6.0 on 2025-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Gifting, Daily Wear', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('image', models.ImageField(upload_to='occasions/')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Occasion',
                'verbose_name_plural': 'Shop Occasions',
                'ordering': ['order'],
            },
        ),
    ]
