# Generated by Django 6.0 on 2025-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bestseller', 'Bestseller'), ('ready_to_wear', 'Ready to Wear'), ('wedding', 'Wedding Collection'), ('festive', 'Festive Wear'), ('daily', 'Daily Wear')], default='bestseller', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ready_to_wear',
            field=models.BooleanField(default=False, help_text='Show in Ready to Wear section'),
        ),
    ]
