# Generated by Django 6.0 on 2025-12-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='policy_agreed',
            field=models.BooleanField(default=False, help_text='Customer agreed to no-return policy'),
        ),
        migrations.AddField(
            model_name='order',
            name='policy_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When policy was agreed', null=True),
        ),
    ]
