# Generated by Django 6.0 on 2025-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_category_product_is_ready_to_wear'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wedding',
            field=models.BooleanField(default=False, help_text='Show in Wedding Vibes section'),
        ),
    ]
