# Generated by Django 6.0 on 2025-12-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cart_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default image for this color'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
