# Generated by Django 6.0 on 2025-12-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='image',
            field=models.ImageField(upload_to='occasions'),
        ),
    ]
