# Generated by Django 6.0 on 2025-12-18 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_occasion_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Testimonial', 'verbose_name_plural': 'Customer Testimonials'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='order',
            new_name='display_order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('saree', 'Saree'), ('gown', 'Gown'), ('kurti', 'Kurti'), ('kurta_set', 'Kurta Set'), ('lehenga', 'Lehenga'), ('other', 'Other')], default='saree', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='products/hover/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_wedding',
            field=models.BooleanField(default=False, help_text='Show in Wedding Collection section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_desktop',
            field=models.ImageField(upload_to='slides/desktop'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to='slides/mobile'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link_url',
            field=models.URLField(blank=True, help_text='Slide click redirect URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='purchase_product',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating out of 5'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', '🟡 Pending Payment'), ('confirmed', '🟢 Payment Confirmed'), ('processing', '📦 Processing'), ('shipped', '🚚 Shipped'), ('delivered', '✅ Delivered'), ('cancelled', '❌ Cancelled'), ('refunded', '💰 Refunded')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, help_text='Courier tracking ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.product')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
