# Generated by Django 6.0 on 2025-12-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_options_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email (optional)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone (optional)', max_length=15)),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('feature', 'Feature Request'), ('design', 'Design Idea'), ('other', 'Other')], default='suggestion', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject', max_length=200)),
                ('message', models.TextField(help_text='Detailed feedback')),
                ('is_approved', models.BooleanField(default=True, help_text='Show publicly')),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark as resolved')),
                ('admin_reply', models.TextField(blank=True, help_text='Admin response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
